### ISSUE TITLE
Write README.md

### ISSUE THREAD

**Issue by toliner** [justincase-jp/AWS-CDK-Kotlin-DSL#24]

**Comment by jonninja** [comment]
Please, just one basic example. Just SOMETHING to show the most basic usage would go a long way.

**Comment by toliner** [comment]
I'm working it on [documentation/readme](https://github.com/justincase-jp/AWS-CDK-Kotlin-DSL/tree/documentation/readme) brunch, and Japanese version is created.
However, translating to English is hard for me because I'm not good at English :(
I will do something for it in a week
